#ifndef IRIS_SPHERE_LIB_DATA_EDGE_COLORS_GLSL
#define IRIS_SPHERE_LIB_DATA_EDGE_COLORS_GLSL 1

// Generated by tools/bake_indexed.py. Rebuild instead of editing.
const int edgeColorOffsets[10] = int[](0, 80, 160, 232, 303, 370, 426, 470, 479, 480);

#endif
