#ifndef IRIS_SPHERE_LIB_DATA_MESH_INFO_GLSL
#define IRIS_SPHERE_LIB_DATA_MESH_INFO_GLSL 1

// Generated by tools/bake_indexed.py. Rebuild instead of editing.
#define VERTEX_COUNT 162
#define TRIANGLE_COUNT 320
#define PARTICLE_GROUPS 3
#define EDGE_COUNT 480
#define EDGE_COLOR_COUNT 9
#define REST_VOLUME 4.047044679979

#endif
