#ifndef IRIS_SPHERE_LIB_CONFIG_CONSTANTS_GLSL
#define IRIS_SPHERE_LIB_CONFIG_CONSTANTS_GLSL 1

#define COLLIDER_CAPACITY 16384
#define ENTITY_GRID_SIZE 16
#define ENTITY_GRID_WORDS 128
const uint ENTITY_CELL_MASK = 15u;
const uint ENTITY_ROW_SHIFT = 4u;
const uint ENTITY_LAYER_SHIFT = 8u;
const uint OCCUPANCY_WORD_BITS = 32u;
const uint OCCUPANCY_WORD_SHIFT = 5u;
const uint OCCUPANCY_BIT_MASK = 31u;
const float ENTITY_CELL_SIZE = 0.5;
#define FLUID_GRID_SIZE 16
#define FLUID_LAYER_COUNT 16
#define FLUID_CELL_COUNT 4096
#define SOLVER_WORKGROUP_SIZE 256
#define CAPTURE_WORKGROUP_SIZE 64
#define MAX_PHYSICS_SUBSTEPS 4
#define MAX_COLLISION_EVENTS 8
#define LOCAL_CONTACT_COUNT 4
const float PHYSICS_TIMESTEP = 1.0 / 120.0;
const float MAX_PARTICLE_SPEED = 12.0;
const float CONTACT_EPSILON = 0.00001;
const float STANDARD_GRAVITY = 9.81;
const float MAX_FRAME_INTERVAL = 0.1;
const float MAX_POSITION_CORRECTION = 0.25;
const float CAPTURE_SAFETY_MARGIN = 0.05;
const float CAPTURE_PADDING = 1.0;
const float TELEPORT_RESET_DISTANCE = 8.0;
const float FLUID_COLUMN_WIDTH = 0.5;
const float FLUID_GRID_LOWER_OFFSET = 4.0;
const float FLUID_SURFACE_BLEND_DEPTH = 0.12;
const float FLUID_HEIGHT_SCALE = 4096.0;
const float FLUID_HEIGHT_TOLERANCE = 0.00025;
const float FLOW_SLOPE_MULTIPLIER = 4.0;
const float TWO_PI = 6.28318530718;
const float FLUID_HEADING_STEPS = 256.0;
const float FLUID_SPEED_STEPS = 255.0;
const uint FLUID_BYTE_MASK = 255u;
const uint FLUID_HEIGHT_SHIFT = 16u;
const uint FLUID_HEADING_SHIFT = 8u;
const float FLUID_MAX_ENCODED_HEIGHT = 65535.0;
const uint EMPTY_SOLID_BOUNDARY = 0xffffffffu;
const int MATERIAL_WATER = 1001;
const int MATERIAL_LAVA = 1002;
const int MATERIAL_PASS_THROUGH = 1003;
const int MEDIUM_SOLID = 0;
const int MEDIUM_WATER = 1;
const int MEDIUM_LAVA = 2;
const float MESH_BOUNDS_PADDING = 0.001;

#endif
