"""Functions for generatin mesh info in shaders/data and shaders/shaders.properties."""

import math
import re
import struct
from collections import Counter

def write_generated_include(path, declarations):
    guard = f"IRIS_SPHERE_LIB_DATA_{path.stem.upper()}_GLSL"
    path.write_text(
        f"#ifndef {guard}\n#define {guard} 1\n\n"
        "// Generated by tools/bake_indexed.py. Rebuild instead of editing.\n"
        f"{declarations}\n\n#endif\n"
    )

def bake(vertices, faces, root):
    
    if not 4 <= len(vertices) <= 256 or not 4 <= len(faces) <= 1024:
        raise ValueError("Single-workgroup solver limit: 256 vertices / 1024 triangles.")

    directed_edges = Counter((face[corner], face[(corner + 1) % 3]) for face in faces for corner in range(3))
    
    if any(count != 1 or directed_edges[(vertex_b, vertex_a)] != 1 for (vertex_a, vertex_b), count in directed_edges.items()):
        raise ValueError("Volume constraints require a closed, consistently wound manifold mesh.")

    edges = sorted({tuple(sorted(edge)) for edge in directed_edges})
    color_groups, occupied_vertices = [], []
    
    for vertex_a, vertex_b in edges:
        color_index = next(
            (
                index
                for index, occupied in enumerate(occupied_vertices)
                if vertex_a not in occupied and vertex_b not in occupied
            ),
            len(color_groups),
        )
        
        if color_index == len(color_groups):
            color_groups.append([])
            occupied_vertices.append(set())
            
        rest_length = math.dist(vertices[vertex_a], vertices[vertex_b])
        color_groups[color_index].append((vertex_a, vertex_b, rest_length, 0.0))
        occupied_vertices[color_index].update((vertex_a, vertex_b))

    adjacency = [[] for _ in vertices]
    rest_volume = 0.0
    
    for face_index, (vertex_a, vertex_b, vertex_c) in enumerate(faces):
    
        for vertex_index in (vertex_a, vertex_b, vertex_c):
            adjacency[vertex_index].append(face_index + 1)
            
        position_a, position_b, position_c = (
            vertices[vertex_a],
            vertices[vertex_b],
            vertices[vertex_c],
        )
        
        rest_volume += (
            sum(
                position_a[axis] * (position_b[(axis + 1) % 3] * position_c[(axis + 2) % 3] - position_b[(axis + 2) % 3] * position_c[(axis + 1) % 3])
                for axis in range(3)
            ) / 6
        )
        
    if rest_volume <= 1e-9:
        raise ValueError("Mesh must have positive signed volume (outward winding).")

    maximum_degree = max(map(len, adjacency))
    
    geometry = root / "shaders/geometry"
    geometry.mkdir(parents=True, exist_ok=True)
    
    (geometry / "sphere_edges.bin").write_bytes(
        b"".join(struct.pack("<4f", *edge) for group in color_groups for edge in group)
    )
    
    (geometry / "sphere_adjacency.bin").write_bytes(
        b"".join(
            struct.pack("<4I", row[column] if column < len(row) else 0, 0, 0, 0)
            for row in adjacency
            for column in range(maximum_degree)
        )
    )
    
    (geometry / "sphere_vertices.bin").write_bytes(
        b"".join(struct.pack("<4f", *position, 1.0) for position in vertices)
    )
    
    (geometry / "sphere_indices.bin").write_bytes(
        b"".join(struct.pack("<4I", *face, 0) for face in faces)
    )
    
    (geometry / "sphere.bin").write_bytes(
        b"".join(
            struct.pack("<4f", *vertices[vertex_index], 1.0)
            for face in faces
            for vertex_index in face
        )
    )

    generated = root / "shaders/lib/data"
    generated.mkdir(parents=True, exist_ok=True)
    write_generated_include(
        generated / "mesh_info.glsl",
        (
            f"#define VERTEX_COUNT {len(vertices)}\n"
            f"#define TRIANGLE_COUNT {len(faces)}\n"
            f"#define PARTICLE_GROUPS {(len(vertices) + 63) // 64}\n"
            f"#define EDGE_COUNT {len(edges)}\n"
            f"#define EDGE_COLOR_COUNT {len(color_groups)}\n"
            f"#define REST_VOLUME {rest_volume:.12f}"
        ),
    )
    
    color_offsets = [0]
    for group in color_groups:
        color_offsets.append(color_offsets[-1] + len(group))
        
    write_generated_include(
        generated / "edge_colors.glsl",
        f"const int edgeColorOffsets[{len(color_offsets)}] = int[]("
        + ", ".join(map(str, color_offsets))
        + ");",
    )

    properties = root / "shaders/shaders.properties"
    text = properties.read_text()
    updates = {
        "bufferObject.1": str(len(vertices) * 48 + 64),
        "customTexture.sphereRest": f"geometry/sphere_vertices.bin TEXTURE_2D RGBA32F {len(vertices)} 1 RGBA FLOAT",
        "customTexture.sphereIndices": f"geometry/sphere_indices.bin TEXTURE_2D RGBA32UI {len(faces)} 1 RGBA_INTEGER UNSIGNED_INT",
        "customTexture.sphereEdges": f"geometry/sphere_edges.bin TEXTURE_2D RGBA32F {len(edges)} 1 RGBA FLOAT",
        "customTexture.sphereAdjacency": f"geometry/sphere_adjacency.bin TEXTURE_2D RGBA32UI {maximum_degree} {len(vertices)} RGBA_INTEGER UNSIGNED_INT",
    }
    
    for key, value in updates.items():
        pattern = r"^" + re.escape(key) + r"=.*$"
        if re.search(pattern, text, re.M):
            text = re.sub(pattern, key + "=" + value, text, flags=re.M)
        else:
            text += key + "=" + value + "\n"
    properties.write_text(text)
