#!/usr/bin/env python3
"""Generates a unit icosphere OBJ and the raw RGBA32F texture read by Iris."""

import argparse
import math
from pathlib import Path


def normalize(position):
    length = math.sqrt(sum(component_a * component_a for component_a in position))
    return tuple(component_a / length for component_a in position)


def sphere(subdivisions):
    golden_ratio = (1 + math.sqrt(5)) / 2
    vertices = [
        normalize(position)
        for position in [
            (-1, golden_ratio, 0),
            (1, golden_ratio, 0),
            (-1, -golden_ratio, 0),
            (1, -golden_ratio, 0),
            (0, -1, golden_ratio),
            (0, 1, golden_ratio),
            (0, -1, -golden_ratio),
            (0, 1, -golden_ratio),
            (golden_ratio, 0, -1),
            (golden_ratio, 0, 1),
            (-golden_ratio, 0, -1),
            (-golden_ratio, 0, 1),
        ]
    ]
    faces = [
        (0, 11, 5),
        (0, 5, 1),
        (0, 1, 7),
        (0, 7, 10),
        (0, 10, 11),
        (1, 5, 9),
        (5, 11, 4),
        (11, 10, 2),
        (10, 7, 6),
        (7, 1, 8),
        (3, 9, 4),
        (3, 4, 2),
        (3, 2, 6),
        (3, 6, 8),
        (3, 8, 9),
        (4, 9, 5),
        (2, 4, 11),
        (6, 2, 10),
        (8, 6, 7),
        (9, 8, 1),
    ]
    for _ in range(subdivisions):
        midpoint_indices = {}

        def midpoint(vertex_a, vertex_b):
            key = tuple(sorted((vertex_a, vertex_b)))
            if key not in midpoint_indices:
                midpoint_indices[key] = len(vertices)
                vertices.append(
                    normalize(
                        tuple(
                            (component_a + component_b) / 2
                            for component_a, component_b in zip(
                                vertices[vertex_a], vertices[vertex_b]
                            )
                        )
                    )
                )
            return midpoint_indices[key]

        subdivided_faces = []
        for vertex_a, vertex_b, vertex_c in faces:
            midpoint_ab, midpoint_bc, midpoint_ca = (
                midpoint(vertex_a, vertex_b),
                midpoint(vertex_b, vertex_c),
                midpoint(vertex_c, vertex_a),
            )
            subdivided_faces.extend(
                [
                    (vertex_a, midpoint_ab, midpoint_ca),
                    (vertex_b, midpoint_bc, midpoint_ab),
                    (vertex_c, midpoint_ca, midpoint_bc),
                    (midpoint_ab, midpoint_bc, midpoint_ca),
                ]
            )
        faces = subdivided_faces
    return vertices, faces


def write_assets(root, subdivisions):
    vertices, faces = sphere(subdivisions)
    assets = root / "assets"
    geometry = root / "shaders" / "geometry"
    assets.mkdir(parents=True, exist_ok=True)
    geometry.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Unit-radius icosphere, centered at model origin.",
        "# Generated by tools/build_sphere.py; Y up; triangles wound outward.",
        "o Sphere",
    ]
    lines += ["v %.9f %.9f %.9f" % position for position in vertices]
    lines += ["vn %.9f %.9f %.9f" % position for position in vertices]
    lines += ["s 1"]
    lines += [
        "f " + " ".join(f"{vertex_index+1}//{vertex_index+1}" for vertex_index in face)
        for face in faces
    ]
    (assets / "sphere.obj").write_text("\n".join(lines) + "\n", encoding="utf-8")
    from bake_indexed import bake

    bake(vertices, faces, root)
    print(f"{len(vertices)} unique particles, {len(faces)} triangles; indexed assets updated.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subdivisions", type=int, choices=range(3), default=2)
    arguments = parser.parse_args()
    write_assets(Path(__file__).resolve().parents[1], arguments.subdivisions)
